connection: &connection
  adapter: mysql2
  pool: 5
  username: root
  password: password
  host: localhost

development:
  <<: *connection
  database: proconsulta_development

test:
  <<: *connection
  database: proconsulta_test

production:
  <<: *connection
  database: proconsulta_production
