connection: &connection
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *connection
  database: proconsulta_development

test:
  <<: *connection
  database: proconsulta_test

production:
  <<: *connection
  database: proconsulta_production
